# Main script that combines each function for this module

import analysis
import analysis_output

Request_headers : {
    "File_ID" : (file_id, type=str) # generated
    "File_URI" : (file_uri, type=str) # given
    "Text" : (raw.txt, type=array) # null, generated by ingester
    "Analyses" : (analyses, type=list) {
        [analysis wanted, type=bool]
    }
}

def text_nlp_analysis(Request_headers)
    # run anlysis based on user requests

    Response_headers : {
        "File_ID" : (file_id, type=str) # generated
        "File_URI" : (file_uri, type=str) # given
        "Analyses" : (analyses, type=object) {
            "Sentiment" : (sentiment, type=str) # null, generated by NPL
            "Keywords" : (keywords, type=list) # ""
            [other analyses results]
        }
    }
    return Response_headers